/* Generated by the Nim Compiler v1.4.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI11592476 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592472 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592468 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592464 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592460 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592456 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592452 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592448 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592444 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592440 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592436 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592432 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592428 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592424 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592420 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592416 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592412 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592408 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592404 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592400 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592396 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592392 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592388 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11592205 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI11592293 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI11592291 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI11593628 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11593619 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI11593618 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI11592385 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI11593626 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI11592387 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI11592269 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI11592267 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI11592661 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI11592273 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI11592271 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI11592659 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI11592657 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI11592289 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI11592287 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI11592655 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI11592653 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI11592277 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI11592275 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI11592651 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI11592241 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI11592239 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI11592233 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI11592614 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI11592612 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI11592235 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI11592610 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI11592237 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI11592675 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI11592281 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI11592279 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI11592673 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI11592767 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI11592285 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI11592283 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI1188064 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI11592231 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI11592229 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI11592245 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI11592243 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI11731017 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI11731015 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI1194649 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1188009 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI1188005 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI11731314 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI1188044 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI1852776 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI1194653 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1194633 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1194637 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI2317015 = {size: 0,kind: 43,base: null,node: null,finalizer: null};
var NTI2317202 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI1194408 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1194728 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI1188015 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI1194723 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI1194617 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1194619 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1194641 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1188013 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI1194641 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1194641.node = NNI1194641;
var NNI1194619 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1194619.node = NNI1194619;
NTI1194723.base = NTI1194617;
NTI1194728.base = NTI1194617;
var NNI1194617 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI1194723, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI1188015, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI1188013, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI1188013, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI1194728, name: "up", sons: null}]};
NTI1194617.node = NNI1194617;
var NNI1194408 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1194408.node = NNI1194408;
NTI1194617.base = NTI1194408;
NTI1194619.base = NTI1194617;
NTI1194641.base = NTI1194619;
var NNI2317202 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a0", len: 0, typ: NTI2317015, name: "a0", sons: null}, 
{kind: 1, offset: "a1", len: 0, typ: NTI2317015, name: "a1", sons: null}]};
NTI2317202.node = NNI2317202;
var NNI1194637 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1194637.node = NNI1194637;
var NNI1194633 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1194633.node = NNI1194633;
NTI1194633.base = NTI1194619;
NTI1194637.base = NTI1194633;
var NNI1194653 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1194653.node = NNI1194653;
NTI1194653.base = NTI1194619;
var NNI1852776 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI1188044, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI1188044, name: "b", sons: null}]};
NTI1852776.node = NNI1852776;
var NNI11731314 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI1188005, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI1188009, name: "b", sons: null}]};
NTI11731314.node = NNI11731314;
var NNI1194649 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1194649.node = NNI1194649;
NTI1194649.base = NTI1194619;
var NNI11731015 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI1188005, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI1188005, name: "Field1", sons: null}]};
NTI11731015.node = NNI11731015;
var NNI11592231 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI11592231.node = NNI11592231;
NTI11592231.base = NTI1194408;
NTI11592229.base = NTI11592231;
NTI11592767.base = NTI11592243;
var NNI11592285 = {kind: 2, len: 10, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "acceptCharset", len: 0, typ: NTI1188015, name: "acceptCharset", sons: null}, 
{kind: 1, offset: "action", len: 0, typ: NTI1188015, name: "action", sons: null}, 
{kind: 1, offset: "autocomplete", len: 0, typ: NTI1188015, name: "autocomplete", sons: null}, 
{kind: 1, offset: "elements", len: 0, typ: NTI11592767, name: "elements", sons: null}, 
{kind: 1, offset: "encoding", len: 0, typ: NTI1188015, name: "encoding", sons: null}, 
{kind: 1, offset: "enctype", len: 0, typ: NTI1188015, name: "enctype", sons: null}, 
{kind: 1, offset: "length", len: 0, typ: NTI1188044, name: "length", sons: null}, 
{kind: 1, offset: "method", len: 0, typ: NTI1188015, name: "method", sons: null}, 
{kind: 1, offset: "noValidate", len: 0, typ: NTI1188064, name: "noValidate", sons: null}, 
{kind: 1, offset: "target", len: 0, typ: NTI1188015, name: "target", sons: null}]};
NTI11592285.node = NNI11592285;
NTI11592285.base = NTI11592245;
NTI11592283.base = NTI11592285;
var NNI11592281 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "defaultSelected", len: 0, typ: NTI1188064, name: "defaultSelected", sons: null}, 
{kind: 1, offset: "selected", len: 0, typ: NTI1188064, name: "selected", sons: null}, 
{kind: 1, offset: "selectedIndex", len: 0, typ: NTI1188044, name: "selectedIndex", sons: null}, 
{kind: 1, offset: "text", len: 0, typ: NTI1188015, name: "text", sons: null}, 
{kind: 1, offset: "value", len: 0, typ: NTI1188015, name: "value", sons: null}]};
NTI11592281.node = NNI11592281;
NTI11592281.base = NTI11592245;
NTI11592279.base = NTI11592281;
NTI11592673.base = NTI11592279;
NTI11592675.base = NTI11592279;
var NNI11592245 = {kind: 2, len: 20, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "className", len: 0, typ: NTI1188015, name: "className", sons: null}, 
{kind: 1, offset: "classList", len: 0, typ: NTI11592229, name: "classList", sons: null}, 
{kind: 1, offset: "checked", len: 0, typ: NTI1188064, name: "checked", sons: null}, 
{kind: 1, offset: "defaultChecked", len: 0, typ: NTI1188064, name: "defaultChecked", sons: null}, 
{kind: 1, offset: "defaultValue", len: 0, typ: NTI1188015, name: "defaultValue", sons: null}, 
{kind: 1, offset: "disabled", len: 0, typ: NTI1188064, name: "disabled", sons: null}, 
{kind: 1, offset: "form", len: 0, typ: NTI11592283, name: "form", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI1188015, name: "name", sons: null}, 
{kind: 1, offset: "readOnly", len: 0, typ: NTI1188064, name: "readOnly", sons: null}, 
{kind: 1, offset: "options", len: 0, typ: NTI11592673, name: "options", sons: null}, 
{kind: 1, offset: "selectedOptions", len: 0, typ: NTI11592675, name: "selectedOptions", sons: null}, 
{kind: 1, offset: "clientWidth", len: 0, typ: NTI1188044, name: "clientWidth", sons: null}, 
{kind: 1, offset: "clientHeight", len: 0, typ: NTI1188044, name: "clientHeight", sons: null}, 
{kind: 1, offset: "contentEditable", len: 0, typ: NTI1188015, name: "contentEditable", sons: null}, 
{kind: 1, offset: "isContentEditable", len: 0, typ: NTI1188064, name: "isContentEditable", sons: null}, 
{kind: 1, offset: "dir", len: 0, typ: NTI1188015, name: "dir", sons: null}, 
{kind: 1, offset: "offsetHeight", len: 0, typ: NTI1188044, name: "offsetHeight", sons: null}, 
{kind: 1, offset: "offsetWidth", len: 0, typ: NTI1188044, name: "offsetWidth", sons: null}, 
{kind: 1, offset: "offsetLeft", len: 0, typ: NTI1188044, name: "offsetLeft", sons: null}, 
{kind: 1, offset: "offsetTop", len: 0, typ: NTI1188044, name: "offsetTop", sons: null}]};
NTI11592245.node = NNI11592245;
NTI11592235.base = NTI11592237;
NTI11592610.base = NTI11592235;
NTI11592612.base = NTI11592235;
NTI11592614.base = NTI11592235;
var NNI11592233 = {kind: 2, offset: 0, typ: null, name: null, len: 12, sons: {"1": {kind: 1, offset: 1, typ: NTI11592233, name: "ElementNode", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI11592233, name: "AttributeNode", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI11592233, name: "TextNode", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI11592233, name: "CDATANode", len: 0, sons: null}, 
"5": {kind: 1, offset: 5, typ: NTI11592233, name: "EntityRefNode", len: 0, sons: null}, 
"6": {kind: 1, offset: 6, typ: NTI11592233, name: "EntityNode", len: 0, sons: null}, 
"7": {kind: 1, offset: 7, typ: NTI11592233, name: "ProcessingInstructionNode", len: 0, sons: null}, 
"8": {kind: 1, offset: 8, typ: NTI11592233, name: "CommentNode", len: 0, sons: null}, 
"9": {kind: 1, offset: 9, typ: NTI11592233, name: "DocumentNode", len: 0, sons: null}, 
"10": {kind: 1, offset: 10, typ: NTI11592233, name: "DocumentTypeNode", len: 0, sons: null}, 
"11": {kind: 1, offset: 11, typ: NTI11592233, name: "DocumentFragmentNode", len: 0, sons: null}, 
"12": {kind: 1, offset: 12, typ: NTI11592233, name: "NotationNode", len: 0, sons: null}}};
NTI11592233.node = NNI11592233;
var NNI11592277 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "text", len: 0, typ: NTI1188015, name: "text", sons: null}, 
{kind: 1, offset: "x", len: 0, typ: NTI1188044, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI1188044, name: "y", sons: null}]};
NTI11592277.node = NNI11592277;
NTI11592277.base = NTI11592245;
NTI11592275.base = NTI11592277;
NTI11592651.base = NTI11592275;
NTI11592653.base = NTI11592283;
var NNI11592289 = {kind: 2, len: 8, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "border", len: 0, typ: NTI1188044, name: "border", sons: null}, 
{kind: 1, offset: "complete", len: 0, typ: NTI1188064, name: "complete", sons: null}, 
{kind: 1, offset: "height", len: 0, typ: NTI1188044, name: "height", sons: null}, 
{kind: 1, offset: "hspace", len: 0, typ: NTI1188044, name: "hspace", sons: null}, 
{kind: 1, offset: "lowsrc", len: 0, typ: NTI1188015, name: "lowsrc", sons: null}, 
{kind: 1, offset: "src", len: 0, typ: NTI1188015, name: "src", sons: null}, 
{kind: 1, offset: "vspace", len: 0, typ: NTI1188044, name: "vspace", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI1188044, name: "width", sons: null}]};
NTI11592289.node = NNI11592289;
NTI11592289.base = NTI11592245;
NTI11592287.base = NTI11592289;
NTI11592655.base = NTI11592287;
NTI11592657.base = NTI11592243;
var NNI11592273 = {kind: 2, len: 6, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "height", len: 0, typ: NTI1188044, name: "height", sons: null}, 
{kind: 1, offset: "hspace", len: 0, typ: NTI1188044, name: "hspace", sons: null}, 
{kind: 1, offset: "src", len: 0, typ: NTI1188015, name: "src", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI1188044, name: "width", sons: null}, 
{kind: 1, offset: "type", len: 0, typ: NTI1188015, name: "type", sons: null}, 
{kind: 1, offset: "vspace", len: 0, typ: NTI1188044, name: "vspace", sons: null}]};
NTI11592273.node = NNI11592273;
NTI11592273.base = NTI11592245;
NTI11592271.base = NTI11592273;
NTI11592659.base = NTI11592271;
var NNI11592269 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "target", len: 0, typ: NTI1188015, name: "target", sons: null}, 
{kind: 1, offset: "text", len: 0, typ: NTI1188015, name: "text", sons: null}, 
{kind: 1, offset: "x", len: 0, typ: NTI1188044, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI1188044, name: "y", sons: null}]};
NTI11592269.node = NNI11592269;
NTI11592269.base = NTI11592245;
NTI11592267.base = NTI11592269;
NTI11592661.base = NTI11592267;
var NNI11593618 = {kind: 1, offset: "then", len: 0, typ: NTI11593619, name: "then", sons: null};
NTI11593618.node = NNI11593618;
NTI11592385.base = NTI11593618;
var NNI11593626 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "ready", len: 0, typ: NTI11592385, name: "ready", sons: null}, 
{kind: 1, offset: "onloadingdone", len: 0, typ: NTI11593628, name: "onloadingdone", sons: null}]};
NTI11593626.node = NNI11593626;
NTI11592387.base = NTI11593626;
var NNI11592241 = {kind: 2, len: 23, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "activeElement", len: 0, typ: NTI11592243, name: "activeElement", sons: null}, 
{kind: 1, offset: "documentElement", len: 0, typ: NTI11592243, name: "documentElement", sons: null}, 
{kind: 1, offset: "alinkColor", len: 0, typ: NTI1188015, name: "alinkColor", sons: null}, 
{kind: 1, offset: "bgColor", len: 0, typ: NTI1188015, name: "bgColor", sons: null}, 
{kind: 1, offset: "body", len: 0, typ: NTI11592243, name: "body", sons: null}, 
{kind: 1, offset: "charset", len: 0, typ: NTI1188015, name: "charset", sons: null}, 
{kind: 1, offset: "cookie", len: 0, typ: NTI1188015, name: "cookie", sons: null}, 
{kind: 1, offset: "defaultCharset", len: 0, typ: NTI1188015, name: "defaultCharset", sons: null}, 
{kind: 1, offset: "fgColor", len: 0, typ: NTI1188015, name: "fgColor", sons: null}, 
{kind: 1, offset: "head", len: 0, typ: NTI11592243, name: "head", sons: null}, 
{kind: 1, offset: "lastModified", len: 0, typ: NTI1188015, name: "lastModified", sons: null}, 
{kind: 1, offset: "linkColor", len: 0, typ: NTI1188015, name: "linkColor", sons: null}, 
{kind: 1, offset: "referrer", len: 0, typ: NTI1188015, name: "referrer", sons: null}, 
{kind: 1, offset: "title", len: 0, typ: NTI1188015, name: "title", sons: null}, 
{kind: 1, offset: "URL", len: 0, typ: NTI1188015, name: "URL", sons: null}, 
{kind: 1, offset: "vlinkColor", len: 0, typ: NTI1188015, name: "vlinkColor", sons: null}, 
{kind: 1, offset: "anchors", len: 0, typ: NTI11592651, name: "anchors", sons: null}, 
{kind: 1, offset: "forms", len: 0, typ: NTI11592653, name: "forms", sons: null}, 
{kind: 1, offset: "images", len: 0, typ: NTI11592655, name: "images", sons: null}, 
{kind: 1, offset: "applets", len: 0, typ: NTI11592657, name: "applets", sons: null}, 
{kind: 1, offset: "embeds", len: 0, typ: NTI11592659, name: "embeds", sons: null}, 
{kind: 1, offset: "links", len: 0, typ: NTI11592661, name: "links", sons: null}, 
{kind: 1, offset: "fonts", len: 0, typ: NTI11592387, name: "fonts", sons: null}]};
NTI11592241.node = NNI11592241;
NTI11592241.base = NTI11592237;
NTI11592239.base = NTI11592241;
var NNI11592293 = {kind: 2, len: 368, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "alignContent", len: 0, typ: NTI1188015, name: "alignContent", sons: null}, 
{kind: 1, offset: "alignItems", len: 0, typ: NTI1188015, name: "alignItems", sons: null}, 
{kind: 1, offset: "alignSelf", len: 0, typ: NTI1188015, name: "alignSelf", sons: null}, 
{kind: 1, offset: "all", len: 0, typ: NTI1188015, name: "all", sons: null}, 
{kind: 1, offset: "animation", len: 0, typ: NTI1188015, name: "animation", sons: null}, 
{kind: 1, offset: "animationDelay", len: 0, typ: NTI1188015, name: "animationDelay", sons: null}, 
{kind: 1, offset: "animationDirection", len: 0, typ: NTI1188015, name: "animationDirection", sons: null}, 
{kind: 1, offset: "animationDuration", len: 0, typ: NTI1188015, name: "animationDuration", sons: null}, 
{kind: 1, offset: "animationFillMode", len: 0, typ: NTI1188015, name: "animationFillMode", sons: null}, 
{kind: 1, offset: "animationIterationCount", len: 0, typ: NTI1188015, name: "animationIterationCount", sons: null}, 
{kind: 1, offset: "animationName", len: 0, typ: NTI1188015, name: "animationName", sons: null}, 
{kind: 1, offset: "animationPlayState", len: 0, typ: NTI1188015, name: "animationPlayState", sons: null}, 
{kind: 1, offset: "animationTimingFunction", len: 0, typ: NTI1188015, name: "animationTimingFunction", sons: null}, 
{kind: 1, offset: "backdropFilter", len: 0, typ: NTI1188015, name: "backdropFilter", sons: null}, 
{kind: 1, offset: "backfaceVisibility", len: 0, typ: NTI1188015, name: "backfaceVisibility", sons: null}, 
{kind: 1, offset: "background", len: 0, typ: NTI1188015, name: "background", sons: null}, 
{kind: 1, offset: "backgroundAttachment", len: 0, typ: NTI1188015, name: "backgroundAttachment", sons: null}, 
{kind: 1, offset: "backgroundBlendMode", len: 0, typ: NTI1188015, name: "backgroundBlendMode", sons: null}, 
{kind: 1, offset: "backgroundClip", len: 0, typ: NTI1188015, name: "backgroundClip", sons: null}, 
{kind: 1, offset: "backgroundColor", len: 0, typ: NTI1188015, name: "backgroundColor", sons: null}, 
{kind: 1, offset: "backgroundImage", len: 0, typ: NTI1188015, name: "backgroundImage", sons: null}, 
{kind: 1, offset: "backgroundOrigin", len: 0, typ: NTI1188015, name: "backgroundOrigin", sons: null}, 
{kind: 1, offset: "backgroundPosition", len: 0, typ: NTI1188015, name: "backgroundPosition", sons: null}, 
{kind: 1, offset: "backgroundRepeat", len: 0, typ: NTI1188015, name: "backgroundRepeat", sons: null}, 
{kind: 1, offset: "backgroundSize", len: 0, typ: NTI1188015, name: "backgroundSize", sons: null}, 
{kind: 1, offset: "blockSize", len: 0, typ: NTI1188015, name: "blockSize", sons: null}, 
{kind: 1, offset: "border", len: 0, typ: NTI1188015, name: "border", sons: null}, 
{kind: 1, offset: "borderBlock", len: 0, typ: NTI1188015, name: "borderBlock", sons: null}, 
{kind: 1, offset: "borderBlockColor", len: 0, typ: NTI1188015, name: "borderBlockColor", sons: null}, 
{kind: 1, offset: "borderBlockEnd", len: 0, typ: NTI1188015, name: "borderBlockEnd", sons: null}, 
{kind: 1, offset: "borderBlockEndColor", len: 0, typ: NTI1188015, name: "borderBlockEndColor", sons: null}, 
{kind: 1, offset: "borderBlockEndStyle", len: 0, typ: NTI1188015, name: "borderBlockEndStyle", sons: null}, 
{kind: 1, offset: "borderBlockEndWidth", len: 0, typ: NTI1188015, name: "borderBlockEndWidth", sons: null}, 
{kind: 1, offset: "borderBlockStart", len: 0, typ: NTI1188015, name: "borderBlockStart", sons: null}, 
{kind: 1, offset: "borderBlockStartColor", len: 0, typ: NTI1188015, name: "borderBlockStartColor", sons: null}, 
{kind: 1, offset: "borderBlockStartStyle", len: 0, typ: NTI1188015, name: "borderBlockStartStyle", sons: null}, 
{kind: 1, offset: "borderBlockStartWidth", len: 0, typ: NTI1188015, name: "borderBlockStartWidth", sons: null}, 
{kind: 1, offset: "borderBlockStyle", len: 0, typ: NTI1188015, name: "borderBlockStyle", sons: null}, 
{kind: 1, offset: "borderBlockWidth", len: 0, typ: NTI1188015, name: "borderBlockWidth", sons: null}, 
{kind: 1, offset: "borderBottom", len: 0, typ: NTI1188015, name: "borderBottom", sons: null}, 
{kind: 1, offset: "borderBottomColor", len: 0, typ: NTI1188015, name: "borderBottomColor", sons: null}, 
{kind: 1, offset: "borderBottomLeftRadius", len: 0, typ: NTI1188015, name: "borderBottomLeftRadius", sons: null}, 
{kind: 1, offset: "borderBottomRightRadius", len: 0, typ: NTI1188015, name: "borderBottomRightRadius", sons: null}, 
{kind: 1, offset: "borderBottomStyle", len: 0, typ: NTI1188015, name: "borderBottomStyle", sons: null}, 
{kind: 1, offset: "borderBottomWidth", len: 0, typ: NTI1188015, name: "borderBottomWidth", sons: null}, 
{kind: 1, offset: "borderCollapse", len: 0, typ: NTI1188015, name: "borderCollapse", sons: null}, 
{kind: 1, offset: "borderColor", len: 0, typ: NTI1188015, name: "borderColor", sons: null}, 
{kind: 1, offset: "borderEndEndRadius", len: 0, typ: NTI1188015, name: "borderEndEndRadius", sons: null}, 
{kind: 1, offset: "borderEndStartRadius", len: 0, typ: NTI1188015, name: "borderEndStartRadius", sons: null}, 
{kind: 1, offset: "borderImage", len: 0, typ: NTI1188015, name: "borderImage", sons: null}, 
{kind: 1, offset: "borderImageOutset", len: 0, typ: NTI1188015, name: "borderImageOutset", sons: null}, 
{kind: 1, offset: "borderImageRepeat", len: 0, typ: NTI1188015, name: "borderImageRepeat", sons: null}, 
{kind: 1, offset: "borderImageSlice", len: 0, typ: NTI1188015, name: "borderImageSlice", sons: null}, 
{kind: 1, offset: "borderImageSource", len: 0, typ: NTI1188015, name: "borderImageSource", sons: null}, 
{kind: 1, offset: "borderImageWidth", len: 0, typ: NTI1188015, name: "borderImageWidth", sons: null}, 
{kind: 1, offset: "borderInline", len: 0, typ: NTI1188015, name: "borderInline", sons: null}, 
{kind: 1, offset: "borderInlineColor", len: 0, typ: NTI1188015, name: "borderInlineColor", sons: null}, 
{kind: 1, offset: "borderInlineEnd", len: 0, typ: NTI1188015, name: "borderInlineEnd", sons: null}, 
{kind: 1, offset: "borderInlineEndColor", len: 0, typ: NTI1188015, name: "borderInlineEndColor", sons: null}, 
{kind: 1, offset: "borderInlineEndStyle", len: 0, typ: NTI1188015, name: "borderInlineEndStyle", sons: null}, 
{kind: 1, offset: "borderInlineEndWidth", len: 0, typ: NTI1188015, name: "borderInlineEndWidth", sons: null}, 
{kind: 1, offset: "borderInlineStart", len: 0, typ: NTI1188015, name: "borderInlineStart", sons: null}, 
{kind: 1, offset: "borderInlineStartColor", len: 0, typ: NTI1188015, name: "borderInlineStartColor", sons: null}, 
{kind: 1, offset: "borderInlineStartStyle", len: 0, typ: NTI1188015, name: "borderInlineStartStyle", sons: null}, 
{kind: 1, offset: "borderInlineStartWidth", len: 0, typ: NTI1188015, name: "borderInlineStartWidth", sons: null}, 
{kind: 1, offset: "borderInlineStyle", len: 0, typ: NTI1188015, name: "borderInlineStyle", sons: null}, 
{kind: 1, offset: "borderInlineWidth", len: 0, typ: NTI1188015, name: "borderInlineWidth", sons: null}, 
{kind: 1, offset: "borderLeft", len: 0, typ: NTI1188015, name: "borderLeft", sons: null}, 
{kind: 1, offset: "borderLeftColor", len: 0, typ: NTI1188015, name: "borderLeftColor", sons: null}, 
{kind: 1, offset: "borderLeftStyle", len: 0, typ: NTI1188015, name: "borderLeftStyle", sons: null}, 
{kind: 1, offset: "borderLeftWidth", len: 0, typ: NTI1188015, name: "borderLeftWidth", sons: null}, 
{kind: 1, offset: "borderRadius", len: 0, typ: NTI1188015, name: "borderRadius", sons: null}, 
{kind: 1, offset: "borderRight", len: 0, typ: NTI1188015, name: "borderRight", sons: null}, 
{kind: 1, offset: "borderRightColor", len: 0, typ: NTI1188015, name: "borderRightColor", sons: null}, 
{kind: 1, offset: "borderRightStyle", len: 0, typ: NTI1188015, name: "borderRightStyle", sons: null}, 
{kind: 1, offset: "borderRightWidth", len: 0, typ: NTI1188015, name: "borderRightWidth", sons: null}, 
{kind: 1, offset: "borderSpacing", len: 0, typ: NTI1188015, name: "borderSpacing", sons: null}, 
{kind: 1, offset: "borderStartEndRadius", len: 0, typ: NTI1188015, name: "borderStartEndRadius", sons: null}, 
{kind: 1, offset: "borderStartStartRadius", len: 0, typ: NTI1188015, name: "borderStartStartRadius", sons: null}, 
{kind: 1, offset: "borderStyle", len: 0, typ: NTI1188015, name: "borderStyle", sons: null}, 
{kind: 1, offset: "borderTop", len: 0, typ: NTI1188015, name: "borderTop", sons: null}, 
{kind: 1, offset: "borderTopColor", len: 0, typ: NTI1188015, name: "borderTopColor", sons: null}, 
{kind: 1, offset: "borderTopLeftRadius", len: 0, typ: NTI1188015, name: "borderTopLeftRadius", sons: null}, 
{kind: 1, offset: "borderTopRightRadius", len: 0, typ: NTI1188015, name: "borderTopRightRadius", sons: null}, 
{kind: 1, offset: "borderTopStyle", len: 0, typ: NTI1188015, name: "borderTopStyle", sons: null}, 
{kind: 1, offset: "borderTopWidth", len: 0, typ: NTI1188015, name: "borderTopWidth", sons: null}, 
{kind: 1, offset: "borderWidth", len: 0, typ: NTI1188015, name: "borderWidth", sons: null}, 
{kind: 1, offset: "bottom", len: 0, typ: NTI1188015, name: "bottom", sons: null}, 
{kind: 1, offset: "boxDecorationBreak", len: 0, typ: NTI1188015, name: "boxDecorationBreak", sons: null}, 
{kind: 1, offset: "boxShadow", len: 0, typ: NTI1188015, name: "boxShadow", sons: null}, 
{kind: 1, offset: "boxSizing", len: 0, typ: NTI1188015, name: "boxSizing", sons: null}, 
{kind: 1, offset: "breakAfter", len: 0, typ: NTI1188015, name: "breakAfter", sons: null}, 
{kind: 1, offset: "breakBefore", len: 0, typ: NTI1188015, name: "breakBefore", sons: null}, 
{kind: 1, offset: "breakInside", len: 0, typ: NTI1188015, name: "breakInside", sons: null}, 
{kind: 1, offset: "captionSide", len: 0, typ: NTI1188015, name: "captionSide", sons: null}, 
{kind: 1, offset: "caretColor", len: 0, typ: NTI1188015, name: "caretColor", sons: null}, 
{kind: 1, offset: "clear", len: 0, typ: NTI1188015, name: "clear", sons: null}, 
{kind: 1, offset: "clip", len: 0, typ: NTI1188015, name: "clip", sons: null}, 
{kind: 1, offset: "clipPath", len: 0, typ: NTI1188015, name: "clipPath", sons: null}, 
{kind: 1, offset: "color", len: 0, typ: NTI1188015, name: "color", sons: null}, 
{kind: 1, offset: "colorAdjust", len: 0, typ: NTI1188015, name: "colorAdjust", sons: null}, 
{kind: 1, offset: "columnCount", len: 0, typ: NTI1188015, name: "columnCount", sons: null}, 
{kind: 1, offset: "columnFill", len: 0, typ: NTI1188015, name: "columnFill", sons: null}, 
{kind: 1, offset: "columnGap", len: 0, typ: NTI1188015, name: "columnGap", sons: null}, 
{kind: 1, offset: "columnRule", len: 0, typ: NTI1188015, name: "columnRule", sons: null}, 
{kind: 1, offset: "columnRuleColor", len: 0, typ: NTI1188015, name: "columnRuleColor", sons: null}, 
{kind: 1, offset: "columnRuleStyle", len: 0, typ: NTI1188015, name: "columnRuleStyle", sons: null}, 
{kind: 1, offset: "columnRuleWidth", len: 0, typ: NTI1188015, name: "columnRuleWidth", sons: null}, 
{kind: 1, offset: "columnSpan", len: 0, typ: NTI1188015, name: "columnSpan", sons: null}, 
{kind: 1, offset: "columnWidth", len: 0, typ: NTI1188015, name: "columnWidth", sons: null}, 
{kind: 1, offset: "columns", len: 0, typ: NTI1188015, name: "columns", sons: null}, 
{kind: 1, offset: "contain", len: 0, typ: NTI1188015, name: "contain", sons: null}, 
{kind: 1, offset: "content", len: 0, typ: NTI1188015, name: "content", sons: null}, 
{kind: 1, offset: "counterIncrement", len: 0, typ: NTI1188015, name: "counterIncrement", sons: null}, 
{kind: 1, offset: "counterReset", len: 0, typ: NTI1188015, name: "counterReset", sons: null}, 
{kind: 1, offset: "counterSet", len: 0, typ: NTI1188015, name: "counterSet", sons: null}, 
{kind: 1, offset: "cursor", len: 0, typ: NTI1188015, name: "cursor", sons: null}, 
{kind: 1, offset: "direction", len: 0, typ: NTI1188015, name: "direction", sons: null}, 
{kind: 1, offset: "display", len: 0, typ: NTI1188015, name: "display", sons: null}, 
{kind: 1, offset: "emptyCells", len: 0, typ: NTI1188015, name: "emptyCells", sons: null}, 
{kind: 1, offset: "filter", len: 0, typ: NTI1188015, name: "filter", sons: null}, 
{kind: 1, offset: "flex", len: 0, typ: NTI1188015, name: "flex", sons: null}, 
{kind: 1, offset: "flexBasis", len: 0, typ: NTI1188015, name: "flexBasis", sons: null}, 
{kind: 1, offset: "flexDirection", len: 0, typ: NTI1188015, name: "flexDirection", sons: null}, 
{kind: 1, offset: "flexFlow", len: 0, typ: NTI1188015, name: "flexFlow", sons: null}, 
{kind: 1, offset: "flexGrow", len: 0, typ: NTI1188015, name: "flexGrow", sons: null}, 
{kind: 1, offset: "flexShrink", len: 0, typ: NTI1188015, name: "flexShrink", sons: null}, 
{kind: 1, offset: "flexWrap", len: 0, typ: NTI1188015, name: "flexWrap", sons: null}, 
{kind: 1, offset: "cssFloat", len: 0, typ: NTI1188015, name: "cssFloat", sons: null}, 
{kind: 1, offset: "font", len: 0, typ: NTI1188015, name: "font", sons: null}, 
{kind: 1, offset: "fontFamily", len: 0, typ: NTI1188015, name: "fontFamily", sons: null}, 
{kind: 1, offset: "fontFeatureSettings", len: 0, typ: NTI1188015, name: "fontFeatureSettings", sons: null}, 
{kind: 1, offset: "fontKerning", len: 0, typ: NTI1188015, name: "fontKerning", sons: null}, 
{kind: 1, offset: "fontLanguageOverride", len: 0, typ: NTI1188015, name: "fontLanguageOverride", sons: null}, 
{kind: 1, offset: "fontOpticalSizing", len: 0, typ: NTI1188015, name: "fontOpticalSizing", sons: null}, 
{kind: 1, offset: "fontSize", len: 0, typ: NTI1188015, name: "fontSize", sons: null}, 
{kind: 1, offset: "fontSizeAdjust", len: 0, typ: NTI1188015, name: "fontSizeAdjust", sons: null}, 
{kind: 1, offset: "fontStretch", len: 0, typ: NTI1188015, name: "fontStretch", sons: null}, 
{kind: 1, offset: "fontStyle", len: 0, typ: NTI1188015, name: "fontStyle", sons: null}, 
{kind: 1, offset: "fontSynthesis", len: 0, typ: NTI1188015, name: "fontSynthesis", sons: null}, 
{kind: 1, offset: "fontVariant", len: 0, typ: NTI1188015, name: "fontVariant", sons: null}, 
{kind: 1, offset: "fontVariantAlternates", len: 0, typ: NTI1188015, name: "fontVariantAlternates", sons: null}, 
{kind: 1, offset: "fontVariantCaps", len: 0, typ: NTI1188015, name: "fontVariantCaps", sons: null}, 
{kind: 1, offset: "fontVariantEastAsian", len: 0, typ: NTI1188015, name: "fontVariantEastAsian", sons: null}, 
{kind: 1, offset: "fontVariantLigatures", len: 0, typ: NTI1188015, name: "fontVariantLigatures", sons: null}, 
{kind: 1, offset: "fontVariantNumeric", len: 0, typ: NTI1188015, name: "fontVariantNumeric", sons: null}, 
{kind: 1, offset: "fontVariantPosition", len: 0, typ: NTI1188015, name: "fontVariantPosition", sons: null}, 
{kind: 1, offset: "fontVariationSettings", len: 0, typ: NTI1188015, name: "fontVariationSettings", sons: null}, 
{kind: 1, offset: "fontWeight", len: 0, typ: NTI1188015, name: "fontWeight", sons: null}, 
{kind: 1, offset: "gap", len: 0, typ: NTI1188015, name: "gap", sons: null}, 
{kind: 1, offset: "grid", len: 0, typ: NTI1188015, name: "grid", sons: null}, 
{kind: 1, offset: "gridArea", len: 0, typ: NTI1188015, name: "gridArea", sons: null}, 
{kind: 1, offset: "gridAutoColumns", len: 0, typ: NTI1188015, name: "gridAutoColumns", sons: null}, 
{kind: 1, offset: "gridAutoFlow", len: 0, typ: NTI1188015, name: "gridAutoFlow", sons: null}, 
{kind: 1, offset: "gridAutoRows", len: 0, typ: NTI1188015, name: "gridAutoRows", sons: null}, 
{kind: 1, offset: "gridColumn", len: 0, typ: NTI1188015, name: "gridColumn", sons: null}, 
{kind: 1, offset: "gridColumnEnd", len: 0, typ: NTI1188015, name: "gridColumnEnd", sons: null}, 
{kind: 1, offset: "gridColumnStart", len: 0, typ: NTI1188015, name: "gridColumnStart", sons: null}, 
{kind: 1, offset: "gridRow", len: 0, typ: NTI1188015, name: "gridRow", sons: null}, 
{kind: 1, offset: "gridRowEnd", len: 0, typ: NTI1188015, name: "gridRowEnd", sons: null}, 
{kind: 1, offset: "gridRowStart", len: 0, typ: NTI1188015, name: "gridRowStart", sons: null}, 
{kind: 1, offset: "gridTemplate", len: 0, typ: NTI1188015, name: "gridTemplate", sons: null}, 
{kind: 1, offset: "gridTemplateAreas", len: 0, typ: NTI1188015, name: "gridTemplateAreas", sons: null}, 
{kind: 1, offset: "gridTemplateColumns", len: 0, typ: NTI1188015, name: "gridTemplateColumns", sons: null}, 
{kind: 1, offset: "gridTemplateRows", len: 0, typ: NTI1188015, name: "gridTemplateRows", sons: null}, 
{kind: 1, offset: "hangingPunctuation", len: 0, typ: NTI1188015, name: "hangingPunctuation", sons: null}, 
{kind: 1, offset: "height", len: 0, typ: NTI1188015, name: "height", sons: null}, 
{kind: 1, offset: "hyphens", len: 0, typ: NTI1188015, name: "hyphens", sons: null}, 
{kind: 1, offset: "imageOrientation", len: 0, typ: NTI1188015, name: "imageOrientation", sons: null}, 
{kind: 1, offset: "imageRendering", len: 0, typ: NTI1188015, name: "imageRendering", sons: null}, 
{kind: 1, offset: "inlineSize", len: 0, typ: NTI1188015, name: "inlineSize", sons: null}, 
{kind: 1, offset: "inset", len: 0, typ: NTI1188015, name: "inset", sons: null}, 
{kind: 1, offset: "insetBlock", len: 0, typ: NTI1188015, name: "insetBlock", sons: null}, 
{kind: 1, offset: "insetBlockEnd", len: 0, typ: NTI1188015, name: "insetBlockEnd", sons: null}, 
{kind: 1, offset: "insetBlockStart", len: 0, typ: NTI1188015, name: "insetBlockStart", sons: null}, 
{kind: 1, offset: "insetInline", len: 0, typ: NTI1188015, name: "insetInline", sons: null}, 
{kind: 1, offset: "insetInlineEnd", len: 0, typ: NTI1188015, name: "insetInlineEnd", sons: null}, 
{kind: 1, offset: "insetInlineStart", len: 0, typ: NTI1188015, name: "insetInlineStart", sons: null}, 
{kind: 1, offset: "isolation", len: 0, typ: NTI1188015, name: "isolation", sons: null}, 
{kind: 1, offset: "justifyContent", len: 0, typ: NTI1188015, name: "justifyContent", sons: null}, 
{kind: 1, offset: "justifyItems", len: 0, typ: NTI1188015, name: "justifyItems", sons: null}, 
{kind: 1, offset: "justifySelf", len: 0, typ: NTI1188015, name: "justifySelf", sons: null}, 
{kind: 1, offset: "left", len: 0, typ: NTI1188015, name: "left", sons: null}, 
{kind: 1, offset: "letterSpacing", len: 0, typ: NTI1188015, name: "letterSpacing", sons: null}, 
{kind: 1, offset: "lineBreak", len: 0, typ: NTI1188015, name: "lineBreak", sons: null}, 
{kind: 1, offset: "lineHeight", len: 0, typ: NTI1188015, name: "lineHeight", sons: null}, 
{kind: 1, offset: "listStyle", len: 0, typ: NTI1188015, name: "listStyle", sons: null}, 
{kind: 1, offset: "listStyleImage", len: 0, typ: NTI1188015, name: "listStyleImage", sons: null}, 
{kind: 1, offset: "listStylePosition", len: 0, typ: NTI1188015, name: "listStylePosition", sons: null}, 
{kind: 1, offset: "listStyleType", len: 0, typ: NTI1188015, name: "listStyleType", sons: null}, 
{kind: 1, offset: "margin", len: 0, typ: NTI1188015, name: "margin", sons: null}, 
{kind: 1, offset: "marginBlock", len: 0, typ: NTI1188015, name: "marginBlock", sons: null}, 
{kind: 1, offset: "marginBlockEnd", len: 0, typ: NTI1188015, name: "marginBlockEnd", sons: null}, 
{kind: 1, offset: "marginBlockStart", len: 0, typ: NTI1188015, name: "marginBlockStart", sons: null}, 
{kind: 1, offset: "marginBottom", len: 0, typ: NTI1188015, name: "marginBottom", sons: null}, 
{kind: 1, offset: "marginInline", len: 0, typ: NTI1188015, name: "marginInline", sons: null}, 
{kind: 1, offset: "marginInlineEnd", len: 0, typ: NTI1188015, name: "marginInlineEnd", sons: null}, 
{kind: 1, offset: "marginInlineStart", len: 0, typ: NTI1188015, name: "marginInlineStart", sons: null}, 
{kind: 1, offset: "marginLeft", len: 0, typ: NTI1188015, name: "marginLeft", sons: null}, 
{kind: 1, offset: "marginRight", len: 0, typ: NTI1188015, name: "marginRight", sons: null}, 
{kind: 1, offset: "marginTop", len: 0, typ: NTI1188015, name: "marginTop", sons: null}, 
{kind: 1, offset: "mask", len: 0, typ: NTI1188015, name: "mask", sons: null}, 
{kind: 1, offset: "maskBorder", len: 0, typ: NTI1188015, name: "maskBorder", sons: null}, 
{kind: 1, offset: "maskBorderMode", len: 0, typ: NTI1188015, name: "maskBorderMode", sons: null}, 
{kind: 1, offset: "maskBorderOutset", len: 0, typ: NTI1188015, name: "maskBorderOutset", sons: null}, 
{kind: 1, offset: "maskBorderRepeat", len: 0, typ: NTI1188015, name: "maskBorderRepeat", sons: null}, 
{kind: 1, offset: "maskBorderSlice", len: 0, typ: NTI1188015, name: "maskBorderSlice", sons: null}, 
{kind: 1, offset: "maskBorderSource", len: 0, typ: NTI1188015, name: "maskBorderSource", sons: null}, 
{kind: 1, offset: "maskBorderWidth", len: 0, typ: NTI1188015, name: "maskBorderWidth", sons: null}, 
{kind: 1, offset: "maskClip", len: 0, typ: NTI1188015, name: "maskClip", sons: null}, 
{kind: 1, offset: "maskComposite", len: 0, typ: NTI1188015, name: "maskComposite", sons: null}, 
{kind: 1, offset: "maskImage", len: 0, typ: NTI1188015, name: "maskImage", sons: null}, 
{kind: 1, offset: "maskMode", len: 0, typ: NTI1188015, name: "maskMode", sons: null}, 
{kind: 1, offset: "maskOrigin", len: 0, typ: NTI1188015, name: "maskOrigin", sons: null}, 
{kind: 1, offset: "maskPosition", len: 0, typ: NTI1188015, name: "maskPosition", sons: null}, 
{kind: 1, offset: "maskRepeat", len: 0, typ: NTI1188015, name: "maskRepeat", sons: null}, 
{kind: 1, offset: "maskSize", len: 0, typ: NTI1188015, name: "maskSize", sons: null}, 
{kind: 1, offset: "maskType", len: 0, typ: NTI1188015, name: "maskType", sons: null}, 
{kind: 1, offset: "maxBlockSize", len: 0, typ: NTI1188015, name: "maxBlockSize", sons: null}, 
{kind: 1, offset: "maxHeight", len: 0, typ: NTI1188015, name: "maxHeight", sons: null}, 
{kind: 1, offset: "maxInlineSize", len: 0, typ: NTI1188015, name: "maxInlineSize", sons: null}, 
{kind: 1, offset: "maxWidth", len: 0, typ: NTI1188015, name: "maxWidth", sons: null}, 
{kind: 1, offset: "minBlockSize", len: 0, typ: NTI1188015, name: "minBlockSize", sons: null}, 
{kind: 1, offset: "minHeight", len: 0, typ: NTI1188015, name: "minHeight", sons: null}, 
{kind: 1, offset: "minInlineSize", len: 0, typ: NTI1188015, name: "minInlineSize", sons: null}, 
{kind: 1, offset: "minWidth", len: 0, typ: NTI1188015, name: "minWidth", sons: null}, 
{kind: 1, offset: "mixBlendMode", len: 0, typ: NTI1188015, name: "mixBlendMode", sons: null}, 
{kind: 1, offset: "objectFit", len: 0, typ: NTI1188015, name: "objectFit", sons: null}, 
{kind: 1, offset: "objectPosition", len: 0, typ: NTI1188015, name: "objectPosition", sons: null}, 
{kind: 1, offset: "offset", len: 0, typ: NTI1188015, name: "offset", sons: null}, 
{kind: 1, offset: "offsetAnchor", len: 0, typ: NTI1188015, name: "offsetAnchor", sons: null}, 
{kind: 1, offset: "offsetDistance", len: 0, typ: NTI1188015, name: "offsetDistance", sons: null}, 
{kind: 1, offset: "offsetPath", len: 0, typ: NTI1188015, name: "offsetPath", sons: null}, 
{kind: 1, offset: "offsetRotate", len: 0, typ: NTI1188015, name: "offsetRotate", sons: null}, 
{kind: 1, offset: "opacity", len: 0, typ: NTI1188015, name: "opacity", sons: null}, 
{kind: 1, offset: "order", len: 0, typ: NTI1188015, name: "order", sons: null}, 
{kind: 1, offset: "orphans", len: 0, typ: NTI1188015, name: "orphans", sons: null}, 
{kind: 1, offset: "outline", len: 0, typ: NTI1188015, name: "outline", sons: null}, 
{kind: 1, offset: "outlineColor", len: 0, typ: NTI1188015, name: "outlineColor", sons: null}, 
{kind: 1, offset: "outlineOffset", len: 0, typ: NTI1188015, name: "outlineOffset", sons: null}, 
{kind: 1, offset: "outlineStyle", len: 0, typ: NTI1188015, name: "outlineStyle", sons: null}, 
{kind: 1, offset: "outlineWidth", len: 0, typ: NTI1188015, name: "outlineWidth", sons: null}, 
{kind: 1, offset: "overflow", len: 0, typ: NTI1188015, name: "overflow", sons: null}, 
{kind: 1, offset: "overflowAnchor", len: 0, typ: NTI1188015, name: "overflowAnchor", sons: null}, 
{kind: 1, offset: "overflowBlock", len: 0, typ: NTI1188015, name: "overflowBlock", sons: null}, 
{kind: 1, offset: "overflowInline", len: 0, typ: NTI1188015, name: "overflowInline", sons: null}, 
{kind: 1, offset: "overflowWrap", len: 0, typ: NTI1188015, name: "overflowWrap", sons: null}, 
{kind: 1, offset: "overflowX", len: 0, typ: NTI1188015, name: "overflowX", sons: null}, 
{kind: 1, offset: "overflowY", len: 0, typ: NTI1188015, name: "overflowY", sons: null}, 
{kind: 1, offset: "overscrollBehavior", len: 0, typ: NTI1188015, name: "overscrollBehavior", sons: null}, 
{kind: 1, offset: "overscrollBehaviorBlock", len: 0, typ: NTI1188015, name: "overscrollBehaviorBlock", sons: null}, 
{kind: 1, offset: "overscrollBehaviorInline", len: 0, typ: NTI1188015, name: "overscrollBehaviorInline", sons: null}, 
{kind: 1, offset: "overscrollBehaviorX", len: 0, typ: NTI1188015, name: "overscrollBehaviorX", sons: null}, 
{kind: 1, offset: "overscrollBehaviorY", len: 0, typ: NTI1188015, name: "overscrollBehaviorY", sons: null}, 
{kind: 1, offset: "padding", len: 0, typ: NTI1188015, name: "padding", sons: null}, 
{kind: 1, offset: "paddingBlock", len: 0, typ: NTI1188015, name: "paddingBlock", sons: null}, 
{kind: 1, offset: "paddingBlockEnd", len: 0, typ: NTI1188015, name: "paddingBlockEnd", sons: null}, 
{kind: 1, offset: "paddingBlockStart", len: 0, typ: NTI1188015, name: "paddingBlockStart", sons: null}, 
{kind: 1, offset: "paddingBottom", len: 0, typ: NTI1188015, name: "paddingBottom", sons: null}, 
{kind: 1, offset: "paddingInline", len: 0, typ: NTI1188015, name: "paddingInline", sons: null}, 
{kind: 1, offset: "paddingInlineEnd", len: 0, typ: NTI1188015, name: "paddingInlineEnd", sons: null}, 
{kind: 1, offset: "paddingInlineStart", len: 0, typ: NTI1188015, name: "paddingInlineStart", sons: null}, 
{kind: 1, offset: "paddingLeft", len: 0, typ: NTI1188015, name: "paddingLeft", sons: null}, 
{kind: 1, offset: "paddingRight", len: 0, typ: NTI1188015, name: "paddingRight", sons: null}, 
{kind: 1, offset: "paddingTop", len: 0, typ: NTI1188015, name: "paddingTop", sons: null}, 
{kind: 1, offset: "pageBreakAfter", len: 0, typ: NTI1188015, name: "pageBreakAfter", sons: null}, 
{kind: 1, offset: "pageBreakBefore", len: 0, typ: NTI1188015, name: "pageBreakBefore", sons: null}, 
{kind: 1, offset: "pageBreakInside", len: 0, typ: NTI1188015, name: "pageBreakInside", sons: null}, 
{kind: 1, offset: "paintOrder", len: 0, typ: NTI1188015, name: "paintOrder", sons: null}, 
{kind: 1, offset: "perspective", len: 0, typ: NTI1188015, name: "perspective", sons: null}, 
{kind: 1, offset: "perspectiveOrigin", len: 0, typ: NTI1188015, name: "perspectiveOrigin", sons: null}, 
{kind: 1, offset: "placeContent", len: 0, typ: NTI1188015, name: "placeContent", sons: null}, 
{kind: 1, offset: "placeItems", len: 0, typ: NTI1188015, name: "placeItems", sons: null}, 
{kind: 1, offset: "placeSelf", len: 0, typ: NTI1188015, name: "placeSelf", sons: null}, 
{kind: 1, offset: "pointerEvents", len: 0, typ: NTI1188015, name: "pointerEvents", sons: null}, 
{kind: 1, offset: "position", len: 0, typ: NTI1188015, name: "position", sons: null}, 
{kind: 1, offset: "quotes", len: 0, typ: NTI1188015, name: "quotes", sons: null}, 
{kind: 1, offset: "resize", len: 0, typ: NTI1188015, name: "resize", sons: null}, 
{kind: 1, offset: "right", len: 0, typ: NTI1188015, name: "right", sons: null}, 
{kind: 1, offset: "rotate", len: 0, typ: NTI1188015, name: "rotate", sons: null}, 
{kind: 1, offset: "rowGap", len: 0, typ: NTI1188015, name: "rowGap", sons: null}, 
{kind: 1, offset: "scale", len: 0, typ: NTI1188015, name: "scale", sons: null}, 
{kind: 1, offset: "scrollBehavior", len: 0, typ: NTI1188015, name: "scrollBehavior", sons: null}, 
{kind: 1, offset: "scrollMargin", len: 0, typ: NTI1188015, name: "scrollMargin", sons: null}, 
{kind: 1, offset: "scrollMarginBlock", len: 0, typ: NTI1188015, name: "scrollMarginBlock", sons: null}, 
{kind: 1, offset: "scrollMarginBlockEnd", len: 0, typ: NTI1188015, name: "scrollMarginBlockEnd", sons: null}, 
{kind: 1, offset: "scrollMarginBlockStart", len: 0, typ: NTI1188015, name: "scrollMarginBlockStart", sons: null}, 
{kind: 1, offset: "scrollMarginBottom", len: 0, typ: NTI1188015, name: "scrollMarginBottom", sons: null}, 
{kind: 1, offset: "scrollMarginInline", len: 0, typ: NTI1188015, name: "scrollMarginInline", sons: null}, 
{kind: 1, offset: "scrollMarginInlineEnd", len: 0, typ: NTI1188015, name: "scrollMarginInlineEnd", sons: null}, 
{kind: 1, offset: "scrollMarginInlineStart", len: 0, typ: NTI1188015, name: "scrollMarginInlineStart", sons: null}, 
{kind: 1, offset: "scrollMarginLeft", len: 0, typ: NTI1188015, name: "scrollMarginLeft", sons: null}, 
{kind: 1, offset: "scrollMarginRight", len: 0, typ: NTI1188015, name: "scrollMarginRight", sons: null}, 
{kind: 1, offset: "scrollMarginTop", len: 0, typ: NTI1188015, name: "scrollMarginTop", sons: null}, 
{kind: 1, offset: "scrollPadding", len: 0, typ: NTI1188015, name: "scrollPadding", sons: null}, 
{kind: 1, offset: "scrollPaddingBlock", len: 0, typ: NTI1188015, name: "scrollPaddingBlock", sons: null}, 
{kind: 1, offset: "scrollPaddingBlockEnd", len: 0, typ: NTI1188015, name: "scrollPaddingBlockEnd", sons: null}, 
{kind: 1, offset: "scrollPaddingBlockStart", len: 0, typ: NTI1188015, name: "scrollPaddingBlockStart", sons: null}, 
{kind: 1, offset: "scrollPaddingBottom", len: 0, typ: NTI1188015, name: "scrollPaddingBottom", sons: null}, 
{kind: 1, offset: "scrollPaddingInline", len: 0, typ: NTI1188015, name: "scrollPaddingInline", sons: null}, 
{kind: 1, offset: "scrollPaddingInlineEnd", len: 0, typ: NTI1188015, name: "scrollPaddingInlineEnd", sons: null}, 
{kind: 1, offset: "scrollPaddingInlineStart", len: 0, typ: NTI1188015, name: "scrollPaddingInlineStart", sons: null}, 
{kind: 1, offset: "scrollPaddingLeft", len: 0, typ: NTI1188015, name: "scrollPaddingLeft", sons: null}, 
{kind: 1, offset: "scrollPaddingRight", len: 0, typ: NTI1188015, name: "scrollPaddingRight", sons: null}, 
{kind: 1, offset: "scrollPaddingTop", len: 0, typ: NTI1188015, name: "scrollPaddingTop", sons: null}, 
{kind: 1, offset: "scrollSnapAlign", len: 0, typ: NTI1188015, name: "scrollSnapAlign", sons: null}, 
{kind: 1, offset: "scrollSnapStop", len: 0, typ: NTI1188015, name: "scrollSnapStop", sons: null}, 
{kind: 1, offset: "scrollSnapType", len: 0, typ: NTI1188015, name: "scrollSnapType", sons: null}, 
{kind: 1, offset: "scrollbar3dLightColor", len: 0, typ: NTI1188015, name: "scrollbar3dLightColor", sons: null}, 
{kind: 1, offset: "scrollbarArrowColor", len: 0, typ: NTI1188015, name: "scrollbarArrowColor", sons: null}, 
{kind: 1, offset: "scrollbarBaseColor", len: 0, typ: NTI1188015, name: "scrollbarBaseColor", sons: null}, 
{kind: 1, offset: "scrollbarColor", len: 0, typ: NTI1188015, name: "scrollbarColor", sons: null}, 
{kind: 1, offset: "scrollbarDarkshadowColor", len: 0, typ: NTI1188015, name: "scrollbarDarkshadowColor", sons: null}, 
{kind: 1, offset: "scrollbarFaceColor", len: 0, typ: NTI1188015, name: "scrollbarFaceColor", sons: null}, 
{kind: 1, offset: "scrollbarHighlightColor", len: 0, typ: NTI1188015, name: "scrollbarHighlightColor", sons: null}, 
{kind: 1, offset: "scrollbarShadowColor", len: 0, typ: NTI1188015, name: "scrollbarShadowColor", sons: null}, 
{kind: 1, offset: "scrollbarTrackColor", len: 0, typ: NTI1188015, name: "scrollbarTrackColor", sons: null}, 
{kind: 1, offset: "scrollbarWidth", len: 0, typ: NTI1188015, name: "scrollbarWidth", sons: null}, 
{kind: 1, offset: "shapeImageThreshold", len: 0, typ: NTI1188015, name: "shapeImageThreshold", sons: null}, 
{kind: 1, offset: "shapeMargin", len: 0, typ: NTI1188015, name: "shapeMargin", sons: null}, 
{kind: 1, offset: "shapeOutside", len: 0, typ: NTI1188015, name: "shapeOutside", sons: null}, 
{kind: 1, offset: "tabSize", len: 0, typ: NTI1188015, name: "tabSize", sons: null}, 
{kind: 1, offset: "tableLayout", len: 0, typ: NTI1188015, name: "tableLayout", sons: null}, 
{kind: 1, offset: "textAlign", len: 0, typ: NTI1188015, name: "textAlign", sons: null}, 
{kind: 1, offset: "textAlignLast", len: 0, typ: NTI1188015, name: "textAlignLast", sons: null}, 
{kind: 1, offset: "textCombineUpright", len: 0, typ: NTI1188015, name: "textCombineUpright", sons: null}, 
{kind: 1, offset: "textDecoration", len: 0, typ: NTI1188015, name: "textDecoration", sons: null}, 
{kind: 1, offset: "textDecorationColor", len: 0, typ: NTI1188015, name: "textDecorationColor", sons: null}, 
{kind: 1, offset: "textDecorationLine", len: 0, typ: NTI1188015, name: "textDecorationLine", sons: null}, 
{kind: 1, offset: "textDecorationSkipInk", len: 0, typ: NTI1188015, name: "textDecorationSkipInk", sons: null}, 
{kind: 1, offset: "textDecorationStyle", len: 0, typ: NTI1188015, name: "textDecorationStyle", sons: null}, 
{kind: 1, offset: "textDecorationThickness", len: 0, typ: NTI1188015, name: "textDecorationThickness", sons: null}, 
{kind: 1, offset: "textEmphasis", len: 0, typ: NTI1188015, name: "textEmphasis", sons: null}, 
{kind: 1, offset: "textEmphasisColor", len: 0, typ: NTI1188015, name: "textEmphasisColor", sons: null}, 
{kind: 1, offset: "textEmphasisPosition", len: 0, typ: NTI1188015, name: "textEmphasisPosition", sons: null}, 
{kind: 1, offset: "textEmphasisStyle", len: 0, typ: NTI1188015, name: "textEmphasisStyle", sons: null}, 
{kind: 1, offset: "textIndent", len: 0, typ: NTI1188015, name: "textIndent", sons: null}, 
{kind: 1, offset: "textJustify", len: 0, typ: NTI1188015, name: "textJustify", sons: null}, 
{kind: 1, offset: "textOrientation", len: 0, typ: NTI1188015, name: "textOrientation", sons: null}, 
{kind: 1, offset: "textOverflow", len: 0, typ: NTI1188015, name: "textOverflow", sons: null}, 
{kind: 1, offset: "textRendering", len: 0, typ: NTI1188015, name: "textRendering", sons: null}, 
{kind: 1, offset: "textShadow", len: 0, typ: NTI1188015, name: "textShadow", sons: null}, 
{kind: 1, offset: "textTransform", len: 0, typ: NTI1188015, name: "textTransform", sons: null}, 
{kind: 1, offset: "textUnderlineOffset", len: 0, typ: NTI1188015, name: "textUnderlineOffset", sons: null}, 
{kind: 1, offset: "textUnderlinePosition", len: 0, typ: NTI1188015, name: "textUnderlinePosition", sons: null}, 
{kind: 1, offset: "top", len: 0, typ: NTI1188015, name: "top", sons: null}, 
{kind: 1, offset: "touchAction", len: 0, typ: NTI1188015, name: "touchAction", sons: null}, 
{kind: 1, offset: "transform", len: 0, typ: NTI1188015, name: "transform", sons: null}, 
{kind: 1, offset: "transformBox", len: 0, typ: NTI1188015, name: "transformBox", sons: null}, 
{kind: 1, offset: "transformOrigin", len: 0, typ: NTI1188015, name: "transformOrigin", sons: null}, 
{kind: 1, offset: "transformStyle", len: 0, typ: NTI1188015, name: "transformStyle", sons: null}, 
{kind: 1, offset: "transition", len: 0, typ: NTI1188015, name: "transition", sons: null}, 
{kind: 1, offset: "transitionDelay", len: 0, typ: NTI1188015, name: "transitionDelay", sons: null}, 
{kind: 1, offset: "transitionDuration", len: 0, typ: NTI1188015, name: "transitionDuration", sons: null}, 
{kind: 1, offset: "transitionProperty", len: 0, typ: NTI1188015, name: "transitionProperty", sons: null}, 
{kind: 1, offset: "transitionTimingFunction", len: 0, typ: NTI1188015, name: "transitionTimingFunction", sons: null}, 
{kind: 1, offset: "translate", len: 0, typ: NTI1188015, name: "translate", sons: null}, 
{kind: 1, offset: "unicodeBidi", len: 0, typ: NTI1188015, name: "unicodeBidi", sons: null}, 
{kind: 1, offset: "verticalAlign", len: 0, typ: NTI1188015, name: "verticalAlign", sons: null}, 
{kind: 1, offset: "visibility", len: 0, typ: NTI1188015, name: "visibility", sons: null}, 
{kind: 1, offset: "whiteSpace", len: 0, typ: NTI1188015, name: "whiteSpace", sons: null}, 
{kind: 1, offset: "widows", len: 0, typ: NTI1188015, name: "widows", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI1188015, name: "width", sons: null}, 
{kind: 1, offset: "willChange", len: 0, typ: NTI1188015, name: "willChange", sons: null}, 
{kind: 1, offset: "wordBreak", len: 0, typ: NTI1188015, name: "wordBreak", sons: null}, 
{kind: 1, offset: "wordSpacing", len: 0, typ: NTI1188015, name: "wordSpacing", sons: null}, 
{kind: 1, offset: "writingMode", len: 0, typ: NTI1188015, name: "writingMode", sons: null}, 
{kind: 1, offset: "zIndex", len: 0, typ: NTI1188015, name: "zIndex", sons: null}]};
NTI11592293.node = NNI11592293;
NTI11592293.base = NTI1194408;
NTI11592291.base = NTI11592293;
var NNI11592237 = {kind: 2, len: 22, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "attributes", len: 0, typ: NTI11592610, name: "attributes", sons: null}, 
{kind: 1, offset: "childNodes", len: 0, typ: NTI11592612, name: "childNodes", sons: null}, 
{kind: 1, offset: "children", len: 0, typ: NTI11592614, name: "children", sons: null}, 
{kind: 1, offset: "data", len: 0, typ: NTI1188015, name: "data", sons: null}, 
{kind: 1, offset: "firstChild", len: 0, typ: NTI11592235, name: "firstChild", sons: null}, 
{kind: 1, offset: "lastChild", len: 0, typ: NTI11592235, name: "lastChild", sons: null}, 
{kind: 1, offset: "nextSibling", len: 0, typ: NTI11592235, name: "nextSibling", sons: null}, 
{kind: 1, offset: "nodeName", len: 0, typ: NTI1188015, name: "nodeName", sons: null}, 
{kind: 1, offset: "nodeType", len: 0, typ: NTI11592233, name: "nodeType", sons: null}, 
{kind: 1, offset: "nodeValue", len: 0, typ: NTI1188015, name: "nodeValue", sons: null}, 
{kind: 1, offset: "parentNode", len: 0, typ: NTI11592235, name: "parentNode", sons: null}, 
{kind: 1, offset: "content", len: 0, typ: NTI11592235, name: "content", sons: null}, 
{kind: 1, offset: "previousSibling", len: 0, typ: NTI11592235, name: "previousSibling", sons: null}, 
{kind: 1, offset: "ownerDocument", len: 0, typ: NTI11592239, name: "ownerDocument", sons: null}, 
{kind: 1, offset: "innerHTML", len: 0, typ: NTI1188015, name: "innerHTML", sons: null}, 
{kind: 1, offset: "outerHTML", len: 0, typ: NTI1188015, name: "outerHTML", sons: null}, 
{kind: 1, offset: "innerText", len: 0, typ: NTI1188015, name: "innerText", sons: null}, 
{kind: 1, offset: "textContent", len: 0, typ: NTI1188015, name: "textContent", sons: null}, 
{kind: 1, offset: "style", len: 0, typ: NTI11592291, name: "style", sons: null}, 
{kind: 1, offset: "baseURI", len: 0, typ: NTI1188015, name: "baseURI", sons: null}, 
{kind: 1, offset: "parentElement", len: 0, typ: NTI11592243, name: "parentElement", sons: null}, 
{kind: 1, offset: "isConnected", len: 0, typ: NTI1188064, name: "isConnected", sons: null}]};
NTI11592237.node = NNI11592237;
var NNI11592205 = {kind: 2, len: 23, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "onabort", len: 0, typ: NTI11592388, name: "onabort", sons: null}, 
{kind: 1, offset: "onblur", len: 0, typ: NTI11592392, name: "onblur", sons: null}, 
{kind: 1, offset: "onchange", len: 0, typ: NTI11592396, name: "onchange", sons: null}, 
{kind: 1, offset: "onclick", len: 0, typ: NTI11592400, name: "onclick", sons: null}, 
{kind: 1, offset: "ondblclick", len: 0, typ: NTI11592404, name: "ondblclick", sons: null}, 
{kind: 1, offset: "onerror", len: 0, typ: NTI11592408, name: "onerror", sons: null}, 
{kind: 1, offset: "onfocus", len: 0, typ: NTI11592412, name: "onfocus", sons: null}, 
{kind: 1, offset: "onkeydown", len: 0, typ: NTI11592416, name: "onkeydown", sons: null}, 
{kind: 1, offset: "onkeypress", len: 0, typ: NTI11592420, name: "onkeypress", sons: null}, 
{kind: 1, offset: "onkeyup", len: 0, typ: NTI11592424, name: "onkeyup", sons: null}, 
{kind: 1, offset: "onload", len: 0, typ: NTI11592428, name: "onload", sons: null}, 
{kind: 1, offset: "onmousedown", len: 0, typ: NTI11592432, name: "onmousedown", sons: null}, 
{kind: 1, offset: "onmousemove", len: 0, typ: NTI11592436, name: "onmousemove", sons: null}, 
{kind: 1, offset: "onmouseout", len: 0, typ: NTI11592440, name: "onmouseout", sons: null}, 
{kind: 1, offset: "onmouseover", len: 0, typ: NTI11592444, name: "onmouseover", sons: null}, 
{kind: 1, offset: "onmouseup", len: 0, typ: NTI11592448, name: "onmouseup", sons: null}, 
{kind: 1, offset: "onreset", len: 0, typ: NTI11592452, name: "onreset", sons: null}, 
{kind: 1, offset: "onselect", len: 0, typ: NTI11592456, name: "onselect", sons: null}, 
{kind: 1, offset: "onsubmit", len: 0, typ: NTI11592460, name: "onsubmit", sons: null}, 
{kind: 1, offset: "onunload", len: 0, typ: NTI11592464, name: "onunload", sons: null}, 
{kind: 1, offset: "onloadstart", len: 0, typ: NTI11592468, name: "onloadstart", sons: null}, 
{kind: 1, offset: "onprogress", len: 0, typ: NTI11592472, name: "onprogress", sons: null}, 
{kind: 1, offset: "onloadend", len: 0, typ: NTI11592476, name: "onloadend", sons: null}]};
NTI11592205.node = NNI11592205;
NTI11592205.base = NTI1194408;
NTI11592237.base = NTI11592205;
NTI11592245.base = NTI11592237;
NTI11592243.base = NTI11592245;
var NNI11731017 = {kind: 2, len: 6, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "pos", len: 0, typ: NTI11731015, name: "pos", sons: null}, 
{kind: 1, offset: "speed", len: 0, typ: NTI11731015, name: "speed", sons: null}, 
{kind: 1, offset: "size", len: 0, typ: NTI1188044, name: "size", sons: null}, 
{kind: 1, offset: "color", len: 0, typ: NTI1188015, name: "color", sons: null}, 
{kind: 1, offset: "element", len: 0, typ: NTI11592243, name: "element", sons: null}, 
{kind: 1, offset: "needReplace", len: 0, typ: NTI1188064, name: "needReplace", sons: null}]};
NTI11731017.node = NNI11731017;
function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);
function nimCopy(dest_1470023, src_1470024, ti_1470025) {
  var result_1475219 = null;

    switch (ti_1470025.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_1465401(ti_1470025))) {
      result_1475219 = src_1470024;
      }
      else {
        result_1475219 = [src_1470024[0], src_1470024[1]];
      }
      
      break;
    case 19:
            if (dest_1470023 === null || dest_1470023 === undefined) {
        dest_1470023 = {};
      }
      else {
        for (var key in dest_1470023) { delete dest_1470023[key]; }
      }
      for (var key in src_1470024) { dest_1470023[key] = src_1470024[key]; }
      result_1475219 = dest_1470023;
    
      break;
    case 18:
    case 17:
      if (!((ti_1470025.base == null))) {
      result_1475219 = nimCopy(dest_1470023, src_1470024, ti_1470025.base);
      }
      else {
      if ((ti_1470025.kind == 17)) {
      result_1475219 = (dest_1470023 === null || dest_1470023 === undefined) ? {m_type: ti_1470025} : dest_1470023;
      }
      else {
        result_1475219 = (dest_1470023 === null || dest_1470023 === undefined) ? {} : dest_1470023;
      }
      }
      nimCopyAux(result_1475219, src_1470024, ti_1470025.node);
      break;
    case 24:
    case 4:
    case 27:
    case 16:
            if (src_1470024 === null) {
        result_1475219 = null;
      }
      else {
        if (dest_1470023 === null || dest_1470023 === undefined) {
          dest_1470023 = new Array(src_1470024.length);
        }
        else {
          dest_1470023.length = src_1470024.length;
        }
        result_1475219 = dest_1470023;
        for (var i = 0; i < src_1470024.length; ++i) {
          result_1475219[i] = nimCopy(result_1475219[i], src_1470024[i], ti_1470025.base);
        }
      }
    
      break;
    case 28:
            if (src_1470024 !== null) {
        result_1475219 = src_1470024.slice(0);
      }
    
      break;
    default: 
      result_1475219 = src_1470024;
      break;
    }

  return result_1475219;

}
function makeNimstrLit(c_1455062) {
      var ln = c_1455062.length;
  var result = new Array(ln);
  for (var i = 0; i < ln; ++i) {
    result[i] = c_1455062.charCodeAt(i);
  }
  return result;
  

  
}
function toJSStr(s_1455096) {
                    var Tmp5;
            var Tmp7;

  var result_1455097 = null;

    var res_1455170 = newSeq_1455128((s_1455096).length);
    var i_1455172 = 0;
    var j_1455174 = 0;
    L1: do {
        L2: while (true) {
        if (!(i_1455172 < (s_1455096).length)) break L2;
          var c_1455175 = s_1455096[i_1455172];
          if ((c_1455175 < 128)) {
          res_1455170[j_1455174] = String.fromCharCode(c_1455175);
          i_1455172 += 1;
          }
          else {
            var helper_1455198 = newSeq_1455128(0);
            L3: do {
                L4: while (true) {
                if (!true) break L4;
                  var code_1455199 = c_1455175.toString(16);
                  if ((((code_1455199) == null ? 0 : (code_1455199).length) == 1)) {
                  helper_1455198.push("%0");;
                  }
                  else {
                  helper_1455198.push("%");;
                  }
                  
                  helper_1455198.push(code_1455199);;
                  i_1455172 += 1;
                    if (((s_1455096).length <= i_1455172)) Tmp5 = true; else {                      Tmp5 = (s_1455096[i_1455172] < 128);                    }                  if (Tmp5) {
                  break L3;
                  }
                  
                  c_1455175 = s_1455096[i_1455172];
                }
            } while(false);
++excHandler;
            Tmp7 = framePtr;
            try {
            res_1455170[j_1455174] = decodeURIComponent(helper_1455198.join(""));
--excHandler;
} catch (EXC) {
 var prevJSError = lastJSError;
 lastJSError = EXC;
 --excHandler;
            framePtr = Tmp7;
            res_1455170[j_1455174] = helper_1455198.join("");
            lastJSError = prevJSError;
            } finally {
            framePtr = Tmp7;
            }
          }
          
          j_1455174 += 1;
        }
    } while(false);
    if (res_1455170.length < j_1455174) { for (var i=res_1455170.length;i<j_1455174;++i) res_1455170.push(null); }
               else { res_1455170.length = j_1455174; };
    result_1455097 = res_1455170.join("");

  return result_1455097;

}
function raiseException(e_1420218, ename_1420219) {
    e_1420218.name = ename_1420219;
    if ((excHandler == 0)) {
    unhandledException(e_1420218);
    }
    
    throw e_1420218;

  
}
function addInt(a_1460419, b_1460420) {
        var result = a_1460419 + b_1460420;
    checkOverflowInt(result);
    return result;
  

  
}
function chckRange(i_1485016, a_1485017, b_1485018) {
      var Tmp1;

  var result_1485019 = 0;

  BeforeRet: do {
      if (!(a_1485017 <= i_1485016)) Tmp1 = false; else {        Tmp1 = (i_1485016 <= b_1485018);      }    if (Tmp1) {
    result_1485019 = i_1485016;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  } while (false);

  return result_1485019;

}
function subInt(a_1460437, b_1460438) {
        var result = a_1460437 - b_1460438;
    checkOverflowInt(result);
    return result;
  

  
}
function mnewString(len_1460044) {
        return new Array(len_1460044);
  

  
}
function cstrToNimstr(c_1455079) {
      var ln = c_1455079.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_1455079.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_1455079.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}
function chckIndx(i_1480086, a_1480087, b_1480088) {
      var Tmp1;

  var result_1480089 = 0;

  BeforeRet: do {
      if (!(a_1480087 <= i_1480086)) Tmp1 = false; else {        Tmp1 = (i_1480086 <= b_1480088);      }    if (Tmp1) {
    result_1480089 = i_1480086;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_1480086, a_1480087, b_1480088);
    }
    
  } while (false);

  return result_1480089;

}
function mulInt(a_1460455, b_1460456) {
        var result = a_1460455 * b_1460456;
    checkOverflowInt(result);
    return result;
  

  
}
function nimFloatToString(a_1460649) {
  var result_1460650 = null;

        function nimOnlyDigitsOrMinus(n) {
      return n.toString().match(/^-?\d+$/);
    }
    if (Number.isSafeInteger(a_1460649)) result_1460650 =  a_1460649+".0"
    else {
      result_1460650 = a_1460649+""
      if(nimOnlyDigitsOrMinus(result_1460650)){
        result_1460650 = a_1460649+".0"
      }
    }
  

  return result_1460650;

}
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var state_2317205 = [{a0: 1773455756, a1: 4275166512}];
if (globalThis.utcInstance_11020231 === undefined) {
  utcInstance_11020231 = [null];
}
if (globalThis.localInstance_11020232 === undefined) {
  localInstance_11020232 = [null];
}
function toFloat_1216659(i_1216661) {
  var result_1216662 = 0.0;

    result_1216662 = i_1216661;

  return result_1216662;

}
function HEX2F_1555648(x_1555650, y_1555651) {
  var result_1555652 = 0.0;

    result_1555652 = (toFloat_1216659(x_1555650) / toFloat_1216659(y_1555651));

  return result_1555652;

}
function epochTime_11590141() {
  var result_11590143 = 0.0;

    result_11590143 = HEX2F_1555648(new Date().getTime(), 1000);

  return result_11590143;

}
function isFatPointer_1465401(ti_1465403) {
  var result_1465404 = false;

  BeforeRet: do {
    result_1465404 = !((ConstSet1[ti_1465403.base.kind] != undefined));
    break BeforeRet;
  } while (false);

  return result_1465404;

}
function nimCopyAux(dest_1470028, src_1470029, n_1470031) {
    switch (n_1470031.kind) {
    case 0:
      break;
    case 1:
            dest_1470028[n_1470031.offset] = nimCopy(dest_1470028[n_1470031.offset], src_1470029[n_1470031.offset], n_1470031.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_1470031.sons.length; i++) {
      nimCopyAux(dest_1470028, src_1470029, n_1470031.sons[i]);
    }
    
      break;
    case 3:
            dest_1470028[n_1470031.offset] = nimCopy(dest_1470028[n_1470031.offset], src_1470029[n_1470031.offset], n_1470031.typ);
      for (var i = 0; i < n_1470031.sons.length; ++i) {
        nimCopyAux(dest_1470028, src_1470029, n_1470031.sons[i][1]);
      }
    
      break;
    }

  
}
function add_1357211(x_1357214, x_1357214_Idx, y_1357215) {
          if (x_1357214[x_1357214_Idx] === null) { x_1357214[x_1357214_Idx] = []; }
      var off = x_1357214[x_1357214_Idx].length;
      x_1357214[x_1357214_Idx].length += y_1357215.length;
      for (var i = 0; i < y_1357215.length; ++i) {
        x_1357214[x_1357214_Idx][off+i] = y_1357215.charCodeAt(i);
      }
    

  
}
function newSeq_1455128(len_1455131) {
  var result_1455133 = [];

    result_1455133 = new Array(len_1455131); for (var i=0;i<len_1455131;++i) {result_1455133[i]=null;}
  return result_1455133;

}
function unhandledException(e_1415059) {
    var buf_1415060 = [[]];
    if (!(((e_1415059.message).length == 0))) {
    buf_1415060[0].push.apply(buf_1415060[0], makeNimstrLit("Error: unhandled exception: "));;
    buf_1415060[0].push.apply(buf_1415060[0], e_1415059.message);;
    }
    else {
    buf_1415060[0].push.apply(buf_1415060[0], makeNimstrLit("Error: unhandled exception"));;
    }
    
    buf_1415060[0].push.apply(buf_1415060[0], makeNimstrLit(" ["));;
    add_1357211(buf_1415060, 0, e_1415059.name);
    buf_1415060[0].push.apply(buf_1415060[0], makeNimstrLit("]\x0A"));;
    var cbuf_1420201 = toJSStr(buf_1415060[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_1420201);
  }
  else {
    throw cbuf_1420201;
  }
  

  
}
function sysFatal_1305418(message_1305422) {
    raiseException({message: nimCopy(null, message_1305422, NTI1188013), m_type: NTI1194641, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}
function raiseAssert_1305414(msg_1305416) {
    sysFatal_1305418(msg_1305416);

  
}
function failedAssertImpl_1305480(msg_1305482) {
    raiseAssert_1305414(msg_1305482);

  
}
function rotl_2317430(x_2317432, k_2317433) {
  var result_2317434 = 0;

    result_2317434 = ((x_2317432 << k_2317433) | ((x_2317432 >>> 0) >>> ((64 - k_2317433) >>> 0)));

  return result_2317434;

}
function next_2317458(r_2317461) {
  var result_2317462 = 0;

    var s0_2317463 = r_2317461.a0;
    var s1_2317464 = r_2317461.a1;
    result_2317462 = ((s0_2317463 + s1_2317464) >>> 0);
    s1_2317464 = (s1_2317464 ^ s0_2317463);
    r_2317461.a0 = ((rotl_2317430(s0_2317463, 55) ^ s1_2317464) ^ (s1_2317464 << 14));
    r_2317461.a1 = rotl_2317430(s1_2317464, 36);

  return result_2317462;

}
function initRand_2340214(seed_2340216) {
  var result_2340217 = [({a0: 0, a1: 0})];

    if (!(!((seed_2340216 == 0)))) {
    failedAssertImpl_1305480(makeNimstrLit("random.nim(568, 12) `seed != 0` "));
    }
    
    result_2340217[0].a0 = Math.floor(seed_2340216 / Math.pow(2,16));
    result_2340217[0].a1 = (seed_2340216 & 65535);
    var _ = next_2317458(result_2340217[0]);

  return result_2340217[0];

}
function randomize_2355222(seed_2355224) {
    nimCopy(state_2317205[0], initRand_2340214(seed_2355224), NTI2317202);

  
}
function randomize_11591001() {
    var time_11591203 = ((epochTime_11590141() * 1.0000000000000000e+03) & 2147483647);
    randomize_2355222(time_11591203);

  
}
function rgb_11725030(r_11725037, g_11725038, b_11725039) {
  var result_11725040 = 0;

    result_11725040 = (((r_11725037 << 16) | (g_11725038 << 8)) | b_11725039);

  return result_11725040;

}
function raiseOverflow() {
    raiseException({message: makeNimstrLit("over- or underflow"), parent: null, m_type: NTI1194637, name: null, trace: [], up: null}, "OverflowDefect");

  
}
function checkOverflowInt(a_1460403) {
        if (a_1460403 > 2147483647 || a_1460403 < -2147483648) raiseOverflow();
  

  
}
function raiseRangeError() {
    raiseException({message: makeNimstrLit("value out of range"), parent: null, m_type: NTI1194653, name: null, trace: [], up: null}, "RangeDefect");

  
}
function rand_2320049(r_2320052, max_2320053) {
  var result_2320054 = 0;

  BeforeRet: do {
    if ((max_2320053 == 0)) {
    break BeforeRet;
    }
    
    L1: do {
        L2: while (true) {
        if (!true) break L2;
          var x_2320055 = next_2317458(r_2320052);
          if ((x_2320055 <= ((4294967295 - (4294967295 % (max_2320053 >>> 0))) >>> 0))) {
          result_2320054 = chckRange((x_2320055 % ((max_2320053 + 1) )), -2147483648, 2147483647);
          break BeforeRet;
          }
          
        }
    } while(false);
  } while (false);

  return result_2320054;

}
function rand_11731090(r_11731093, x_11731095) {
  var result_11731096 = 0;

    result_11731096 = addInt(rand_2320049(r_11731093, chckRange(subInt(x_11731095.b, x_11731095.a), 0, 2147483647)), x_11731095.a);

  return result_11731096;

}
function rand_11731065(x_11731069) {
  var result_11731070 = 0;

    result_11731070 = rand_11731090(state_2317205[0], x_11731069);

  return result_11731070;

}
function HEX2EHEX2E_3430220(a_3430225, b_3430227) {
  var result_3430229 = ({a: 0, b: 0});

    nimCopy(result_3430229, {a: a_3430225, b: b_3430227}, NTI1852776);

  return result_3430229;

}
function rand_2320087(r_2320090, max_2320113) {
  var result_2320114 = 0.0;

    var x_2320115 = next_2317458(r_2320090);
    result_2320114 = ((x_2320115 / 4294967295) * max_2320113);

  return result_2320114;

}
function rand_11731412(r_11731415, x_11731417) {
  var result_11731418 = 0.0;

    result_11731418 = (rand_2320087(r_11731415, chckRange((x_11731417.b - x_11731417.a), 0.0, Infinity)) + x_11731417.a);

  return result_11731418;

}
function rand_11731387(x_11731391) {
  var result_11731392 = 0.0;

    result_11731392 = rand_11731412(state_2317205[0], x_11731391);

  return result_11731392;

}
function HEX2EHEX2E_11731304(a_11731309, b_11731311) {
  var result_11731317 = ({a: 0.0, b: 0.0});

    nimCopy(result_11731317, {a: a_11731309, b: b_11731311}, NTI11731314);

  return result_11731317;

}
function raiseIndexError(i_1440047, a_1440048, b_1440049) {
    var Tmp1;

    if ((b_1440049 < a_1440048)) {
    Tmp1 = makeNimstrLit("index out of bounds, the container is empty");
    }
    else {
    Tmp1 = (makeNimstrLit("index ") || []).concat(cstrToNimstr((i_1440047)+"") || [],makeNimstrLit(" not in ") || [],cstrToNimstr((a_1440048)+"") || [],makeNimstrLit(" .. ") || [],cstrToNimstr((b_1440049)+"") || []);
    }
    
    raiseException({message: nimCopy(null, Tmp1, NTI1188013), parent: null, m_type: NTI1194649, name: null, trace: [], up: null}, "IndexDefect");

  
}
function toHexImpl_9750241(x_9750243, len_9750244, handleNegative_9750245) {
  var result_9750246 = [];

    var n_9750248 = x_9750243;
    result_9750246 = nimCopy(null, mnewString(len_9750244), NTI1188013);
    L1: do {
      var j_9750255 = 0;
      var colontmp__11750505 = 0;
      colontmp__11750505 = subInt(len_9750244, 1);
      var res_11750510 = colontmp__11750505;
      L2: do {
          L3: while (true) {
          if (!(0 <= res_11750510)) break L3;
            j_9750255 = res_11750510;
            result_9750246[chckIndx(j_9750255, 0, (result_9750246).length-1)] = makeNimstrLit("0123456789ABCDEF")[chckIndx((n_9750248 & 15), 0, (makeNimstrLit("0123456789ABCDEF")).length-1)];
            n_9750248 = ((n_9750248 >>> 0) >>> 4);
            if (((n_9750248 == 0) && handleNegative_9750245)) {
            n_9750248 = 4294967295;
            }
            
            res_11750510 = subInt(res_11750510, 1);
          }
      } while(false);
    } while(false);

  return result_9750246;

}
function toHex_10210145(x_10210148, len_10210149) {
  var result_10210150 = [];

    result_10210150 = nimCopy(null, toHexImpl_9750241((x_10210148 >>> 0), len_10210149, (x_10210148 < 0)), NTI1188013);

  return result_10210150;

}
function HEX24_11705488(c_11705490) {
  var result_11705491 = [];

    result_11705491 = nimCopy(null, [35].concat(toHex_10210145(c_11705490, 6) || []), NTI1188013);

  return result_11705491;

}
function initBall_11731029() {
  var result_11731031 = ({pos: {Field0: 0.0, Field1: 0.0}, speed: {Field0: 0.0, Field1: 0.0}, size: 0, color: null, element: null, needReplace: false});

  BeforeRet: do {
    randomize_11591001();
    var element_11731032 = document.createElement("span");
    var color_11731302 = rgb_11725030(chckRange(rand_11731065(HEX2EHEX2E_3430220(0, 255)), 0, 255), chckRange(rand_11731065(HEX2EHEX2E_3430220(0, 255)), 0, 255), chckRange(rand_11731065(HEX2EHEX2E_3430220(0, 255)), 0, 255));
    var pos_11731663 = {Field0: rand_11731387(HEX2EHEX2E_11731304(-2.0000000000000000e+01, 1.2000000000000000e+02)), Field1: rand_11731387(HEX2EHEX2E_11731304(-2.0000000000000000e+01, 1.2000000000000000e+02))};
    var speed_11731733 = {Field0: rand_11731387(HEX2EHEX2E_11731304(-5.0000000000000000e+01, 5.0000000000000000e+01)), Field1: rand_11731387(HEX2EHEX2E_11731304(-5.0000000000000000e+01, 5.0000000000000000e+01))};
    var size_11731770 = rand_11731065(HEX2EHEX2E_3430220(1, 20));
    element_11731032.className = "ball shadow";
    nimCopy(result_11731031, {color: toJSStr(HEX24_11705488(color_11731302)), pos: nimCopy(null, pos_11731663, NTI11731015), speed: nimCopy(null, speed_11731733, NTI11731015), size: size_11731770, element: element_11731032, needReplace: false}, NTI11731017);
    break BeforeRet;
  } while (false);

  return result_11731031;

}
function HEX2BHEX3D_10280021(x_10280025, x_10280025_Idx, y_10280026) {
    x_10280025[x_10280025_Idx] = (x_10280025[x_10280025_Idx] + y_10280026);

  
}
function configElement_11731829(self_11731832) {
    self_11731832.element.style.setProperty("--color", self_11731832.color, []);
    self_11731832.element.style.setProperty("--size", toJSStr((cstrToNimstr((self_11731832.size)+"") || []).concat(makeNimstrLit("em") || [])), []);
    self_11731832.element.style.setProperty("--x", toJSStr((cstrToNimstr(nimFloatToString(self_11731832.pos.Field0)) || []).concat(makeNimstrLit("%") || [])), []);
    self_11731832.element.style.setProperty("--y", toJSStr((cstrToNimstr(nimFloatToString(self_11731832.pos.Field1)) || []).concat(makeNimstrLit("%") || [])), []);

  
}
function update_11731846(self_11731849) {
      var Tmp1;
      var Tmp2;
      var Tmp3;

    HEX2BHEX3D_10280021(self_11731849.pos, "Field0", (self_11731849.speed.Field0 / 1.0000000000000000e+02));
    HEX2BHEX3D_10280021(self_11731849.pos, "Field1", (self_11731849.speed.Field1 / 1.0000000000000000e+02));
    var limit_11731875 = {Field0: {Field0: (mulInt(self_11731849.size, -2) / 5.0000000000000000e-01), Field1: (mulInt(self_11731849.size, -2) / 5.0000000000000000e-01)}, Field1: {Field0: (1.0000000000000000e+02 + self_11731849.size), Field1: (1.0000000000000000e+02 + self_11731849.size)}};
      if ((self_11731849.pos.Field0 < limit_11731875.Field0.Field0)) Tmp3 = true; else {        Tmp3 = (self_11731849.pos.Field1 < limit_11731875.Field0.Field1);      }      if (Tmp3) Tmp2 = true; else {        Tmp2 = (limit_11731875.Field1.Field0 < self_11731849.pos.Field0);      }      if (Tmp2) Tmp1 = true; else {        Tmp1 = (limit_11731875.Field1.Field1 < self_11731849.pos.Field1);      }    if (Tmp1) {
    self_11731849.needReplace = true;
    }
    
    configElement_11731829(self_11731849);

  
}
function HEX3Aanonymous_11741054() {
    var ball_11741056 = [initBall_11731029()];
    var Tmp1 = nimCopy(null, ball_11741056[0], NTI11731017);
    balls_11741044[0].push(Tmp1);;
    container_11741027.appendChild(ball_11741056[0].element);
    update_11731846(ball_11741056[0]);

  
}
function HEX3Aanonymous_11741095() {
    L1: do {
      var ball_11750215 = null;
      var i_11750530 = 0;
      var L_11750531 = (balls_11741044[0]).length;
      L2: do {
          L3: while (true) {
          if (!(i_11750530 < L_11750531)) break L3;
            ball_11750215 = balls_11741044[0][chckIndx(i_11750530, 0, (balls_11741044[0]).length-1)];
            update_11731846(ball_11750215);
            if (ball_11750215.needReplace) {
            ball_11750215.element.remove();
            nimCopy(ball_11750215, initBall_11731029(), NTI11731017);
            container_11741027.appendChild(ball_11750215.element);
            }
            
            i_11750530 = addInt(i_11750530, 1);
            if (!(((balls_11741044[0]).length == L_11750531))) {
            failedAssertImpl_1305480(makeNimstrLit("iterators.nim(213, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      } while(false);
    } while(false);

  
}
var container_11741027 = document.querySelector("div.bg");
var balls_11741044 = [[]];
L1: do {
  var i_11741053 = [0];
  var i_11750475 = 0;
  L2: do {
      L3: while (true) {
      if (!(i_11750475 < 20)) break L3;
        i_11741053[0] = i_11750475;
        var _ = window.setTimeout(HEX3Aanonymous_11741054, mulInt(i_11741053[0], 200));
        i_11750475 = addInt(i_11750475, 1);
      }
  } while(false);
} while(false);
var _ = window.setInterval(HEX3Aanonymous_11741095, 150);
